# This is a basic workflow that is manually triggered

name: Trigger Python Create File Workflow

on:
  schedule:
    # Run the workflow at 12:00 AM UTC every day
    - cron: '*/5 * * * *'

jobs:
  python-job:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository so we can access the files
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # You can specify the exact version if needed

    # Install dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Skip this if you don't have dependencies

    # Run the Python script (assuming your script is named create_file.py)
    - name: Run Python script
      run: |
        python create_file.py

    # Optionally, print a message when done
    - name: Done
      run: echo "Python script has been executed"
